In [4]:
import numpy as np
arr = np.arange(100).reshape(5, -1)
arr2 = arr[:, :4]
print(arr)
print(arr2)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [5]:
from matplotlib import pyplot as plt
fig = plt.figure()
ax = fig.add_axes([0,0,1,1], label='ax')
ax.set_xlabel("X-axis")
ax.set_ylabel("Y-axis")
x = [0, 100]
y = [0, 200]
ax.plot(x, y, color='red', )

Matplotlib is building the font cache; this may take a moment.


In [13]:
from matplotlib import pyplot as plt
import pandas as pd

df = pd.read_csv('company_sales_data.csv')
fig = plt.figure()
months = df['month_number'].values
total_profit = df['total_profit'].values
ax = fig.add_axes([0,0,1,1])
ax.set_xlabel("Month")
ax.set_ylabel("Total Profit")
ax.plot(months, total_profit, color='blue', marker='o', linestyle='--')

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from matplotlib import pyplot as plt
import numpy as np

df = pd.read_csv('diabetes_csv.csv')
print(type(df['Pregnancies'] > 0))
df.drop(['Pregnancies'], axis=1, inplace=True)
data_arr = df.values
X = data_arr[:, :-1]
y = data_arr[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Study Data
df = pd.read_csv('study_data.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
X_train = X_train.reshape(-1,)

# Pedhazur
X_mean = np.mean(X_train)
y_mean = np.mean(y_train)
b1 = (np.sum((X_train - X_mean) * (y_train - y_mean))) / (np.sum((X_train - X_mean) ** 2))
b0 = y_mean - b1 * X_mean

y_pred = b0 + b1 * X_test.reshape(-1,)
print(X_test.flatten(), y_test, y_pred, np.sqrt(np.mean((y_pred - y_test) ** 2)))

# Calculus
X_sum = np.sum(X_train)
y_sum = np.sum(y_train)
X2_sum = np.sum(X_train ** 2)
Xy_sum = np.sum(X_train * y_train)
n = len(X_train)

b1 = (n * Xy_sum - X_sum * y_sum) / (n * X2_sum - X_sum ** 2)
b0 = (y_sum - b1 * X_sum) / n

y_pred = b0 + b1 * X_test.flatten()
print(X_test.flatten(), y_test, y_pred, np.sqrt(np.mean((y_pred - y_test) ** 2)))

plt.scatter(X, y, label='Actual Data')
plt.plot(X_test, y_pred, label='predicted')
plt.xlabel('Study Time')

[ 9 10  2] [10 12  4] [ 9.20491803 10.08196721  3.06557377] 1.3145541049531033
[ 9 10  2] [10 12  4] [ 9.20491803 10.08196721  3.06557377] 1.3145541049531038


Text(0.5, 0, 'Study Time')

KeyError: 'Study Time'