In [5]:
import pandas as pd
import numpy as np
def p(o):
  print(o)
  print()

In [20]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],'name': ['a', 'a', 'a', 'b', 'b'], 'price': [12.33,11.44,33.21,13.23,33.62]})
frame2 = pd.DataFrame({'id': ['pencil','pencil','ball','pen'], 'name': ['a', 'a', 'b', 'c'], 'color': ['white','red','red','black']})
p(frame1)
p(frame2)
p(pd.merge(frame1, frame2, on=['id']))
p(pd.merge(frame1, frame2, how='right'))
p(pd.merge(frame1, frame2, how='left'))
p(pd.merge(frame1, frame2, how='outer'))


        id name  price
0     ball    a  12.33
1   pencil    a  11.44
2      pen    a  33.21
3      mug    b  13.23
4  ashtray    b  33.62

       id name  color
0  pencil    a  white
1  pencil    a    red
2    ball    b    red
3     pen    c  black

       id name_x  price name_y  color
0    ball      a  12.33      b    red
1  pencil      a  11.44      a  white
2  pencil      a  11.44      a    red
3     pen      a  33.21      c  black

       id name  price  color
0  pencil    a  11.44  white
1  pencil    a  11.44    red
2    ball    b    NaN    red
3     pen    c    NaN  black

        id name  price  color
0     ball    a  12.33    NaN
1   pencil    a  11.44  white
2   pencil    a  11.44    red
3      pen    a  33.21    NaN
4      mug    b  13.23    NaN
5  ashtray    b  33.62    NaN

        id name  price  color
0  ashtray    b  33.62    NaN
1     ball    a  12.33    NaN
2     ball    b    NaN    red
3      mug    b  13.23    NaN
4      pen    a  33.21    NaN
5      pen    c    NaN

In [32]:
p(pd.concat([frame1, frame2], axis=0))
p(pd.concat([frame1, frame2], axis=1))
p(frame1.join(frame2, lsuffix='_l', rsuffix='_r'))
p(frame1.combine_first(frame2))

        id name  price  color
0     ball    a  12.33    NaN
1   pencil    a  11.44    NaN
2      pen    a  33.21    NaN
3      mug    b  13.23    NaN
4  ashtray    b  33.62    NaN
0   pencil    a    NaN  white
1   pencil    a    NaN    red
2     ball    b    NaN    red
3      pen    c    NaN  black

        id name  price      id name  color
0     ball    a  12.33  pencil    a  white
1   pencil    a  11.44  pencil    a    red
2      pen    a  33.21    ball    b    red
3      mug    b  13.23     pen    c  black
4  ashtray    b  33.62     NaN  NaN    NaN

      id_l name_l  price    id_r name_r  color
0     ball      a  12.33  pencil      a  white
1   pencil      a  11.44  pencil      a    red
2      pen      a  33.21    ball      b    red
3      mug      b  13.23     pen      c  black
4  ashtray      b  33.62     NaN    NaN    NaN

   color       id name  price
0  white     ball    a  12.33
1    red   pencil    a  11.44
2    red      pen    a  33.21
3  black      mug    b  13.23
4    Na

In [36]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'], 'value': [2,1,3,3,2]})
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

In [47]:
a = np.arange(1, 10).reshape(3,3)
p(a)
p(a.sum(axis=0))
p(a.sum(axis=1))
p(a.std(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[12 15 18]

[ 6 15 24]

[0.81649658 0.81649658 0.81649658]



In [60]:
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]
bins = [0,25,50,75,100]
a = pd.cut(results, bins)
a.value_counts()
pd.qcut(results, q=4).value_counts()

(2.999, 28.0]    5
(28.0, 55.0]     4
(55.0, 87.0]     5
(87.0, 99.0]     3
Name: count, dtype: int64

In [83]:
a = pd.DataFrame(np.random.randn(9, 3))
p(a)
b = np.random.permutation(3)
p(b)
c = np.random.randint(0, len(a), size=5)
p(c)
p(a.take(b))
p(a.take(c))

          0         1         2
0  0.643957  0.280958 -0.056089
1  0.818225 -0.419939 -0.510617
2  0.629852  1.615799  1.358645
3 -0.005345  2.454903  0.399155
4  1.293001  1.784138 -0.162916
5  0.831118 -0.916024  0.297600
6  0.913233 -1.071772  0.036292
7  0.361496  1.595464 -0.140473
8 -0.364809  2.946516 -0.868314

[0 2 1]

[6 6 3 4 5]

          0         1         2
0  0.643957  0.280958 -0.056089
2  0.629852  1.615799  1.358645
1  0.818225 -0.419939 -0.510617

          0         1         2
6  0.913233 -1.071772  0.036292
6  0.913233 -1.071772  0.036292
3 -0.005345  2.454903  0.399155
4  1.293001  1.784138 -0.162916
5  0.831118 -0.916024  0.297600



In [ ]:
frame = pd.DataFrame({ 'color': ['white','red','green','red','green'], 'object': ['pen','pencil','pencil','ashtray','pen'], 'price1' : [5.56,4.20,1.30,0.56,2.75], 'price2' : [4.75,4.12,1.60,0.75,3.15]})

g = frame['price1'].groupby(frame['color'])
p(g.mean())
p(g.sum())

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64



color
green    4.05
red      4.76
white    5.56
Name: price1, dtype: float64